// TARGET ELEMENT
loveLine = document.getElementById("love-line")

// ALL 100 LOVE LINES
loveLines = [
  "the way someone remembers your order without asking.",
  "silence that feels like a warm blanket, not a wall.",
  "choosing someone even when you’re tired.",
  "a soft place to land after a hard day.",
  "laughing at something only the two of you understand.",
  "giving the last bite even though you wanted it.",
  "letting someone see you cry without looking away.",
  "two people carrying the same secret.",
  "someone remembering your birthday without a reminder.",
  "showing up even when you don’t know what to say.",
  "a text that says ‘home yet?’",
  "the way they look at you when you’re not watching.",
  "keeping your photo in their phone for years.",
  "holding hands in a grocery store.",
  "wanting to tell them good news first.",
  "staying curious about someone after years.",
  "soft eyes when you’re wrong but trying.",
  "the safety of being fully yourself.",
  "forgetting you were scared.",
  "hearing ‘you’re not alone’ at your lowest.",
  "leaving the light on for someone coming home late.",
  "remembering a story they told you months ago.",
  "wanting them to eat before you do.",
  "‘drive safe’ meaning ‘I can’t lose you.’",
  "laughing until your stomach hurts.",
  "missing someone even when they’re beside you.",
  "trusting someone with the unlovable parts.",
  "‘did you sleep okay?’",
  "brushing lint off their sweater.",
  "being brave together.",
  "choosing kindness in an argument.",
  "folding towels the way they like.",
  "a slow promise that says ‘I’m here.’",
  "wanting to understand, not win.",
  "hearing your name like it’s a gift.",
  "someone smiling at your voice.",
  "holding their bag without being asked.",
  "listening to a song because of them.",
  "calling them back even if you’re upset.",
  "hoping they get home safe.",
  "remembering their laugh better than their face.",
  "warmth that stays after the hug ends.",
  "choosing them again in your dreams.",
  "being gentle with someone’s fear.",
  "saying ‘I’m sorry’ first.",
  "wanting to grow in the same direction.",
  "building a tiny world between two hearts.",
  "sitting closer when you’re sad.",
  "letting someone see your mess.",
  "feeling safe enough to fall apart.",
  "being known without explaining.",
  "choosing someone’s flaws with love.",
  "moments no one else notices.",
  "letting go when staying hurts more.",
  "closing the distance between two scared hearts.",
  "a ‘good morning’ that changes the day.",
  "saving a piece of the day for someone.",
  "the courage to try again.",
  "believing in each other’s futures.",
  "someone waiting for you to catch up.",
  "remembering the way they like their coffee.",
  "not having to pretend.",
  "someone noticing you’re quiet.",
  "the courage to tell the truth.",
  "sharing an umbrella in the rain.",
  "sitting on the floor together for no reason.",
  "feeling seen in a crowded room.",
  "a hand on your back saying ‘I’m here.’",
  "someone keeping your secrets safe.",
  "letting someone sleep on your shoulder.",
  "choosing each other on ordinary days.",
  "a soft ‘are you okay?’",
  "someone checking in when they’re busy.",
  "being held when you fall apart.",
  "the warmth in someone’s voice.",
  "a gentle ‘take your time.’",
  "wanting to stay a little longer.",
  "breathing easier near someone.",
  "noticing tiny changes in them.",
  "waiting for their message even when tired.",
  "feeling understood without explaining.",
  "being known in the quiet moments.",
  "keeping each other warm in small ways.",
  "wanting them to get home safe.",
  "someone remembering your favorite song.",
  "choosing softness over pride.",
  "noticing their smile first.",
  "leaving room for their sadness.",
  "feeling like you belong.",
  "wanting to be better for someone.",
  "holding the door a little longer.",
  "picking them up when they fall.",
  "feeling safe in someone's arms.",
  "learning each other’s rhythms.",
  "forgiving and still holding the lesson.",
  "missing them before they leave.",
  "saving the last seat for someone.",
  "seeing the best in them on bad days.",
  "a soft place to rest your heart.",
  "when I saw that subway ad saying more than 400 people in New York die waiting for an organ, I don’t know why, but I thought of you. I just knew that if you ever needed mine, I’d give it to you. <br><br>P.S. If you get this on the first try, you’re really special. Not everyone is meant to."
]

// RANDOM LINE
lineIndex = Math.floor(Math.random() * loveLines.length)
loveLine.innerHTML = loveLines[lineIndex]
